services:
  db:
    container_name: "stratmakerDB"
    image: postgres:12.4-alpine
    volumes:
      - "./database/postgres-data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: unless-stopped

  redis:
    container_name: "stratmakerRedis"
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - "./database/redis-data:/data"

  db_test:
    container_name: "stratmakerDB_test"
    image: postgres:12.4-alpine
    tmpfs:
      - /var/lib/postgresql/data:rw,noexec,nosuid,size=512m
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: "test_postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: unless-stopped

  redis_test:
    container_name: "stratmakerRedis_test"
    image: redis:7-alpine
    ports:
      - "6380:6379"
    command: redis-server --appendonly no
    tmpfs:
      - /data:rw,noexec,nosuid,size=128m
